services:
  postgres:
    image: postgres:17
    container_name: sale-market-postgres
    restart: always
    environment:
      POSTGRES_USER: sale_user
      POSTGRES_PASSWORD: sale_password
      POSTGRES_DB: sale_market
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sale-network

  sale-app:
    build: .
    container_name: sale_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sale_market
      SPRING_DATASOURCE_USERNAME: sale_user
      SPRING_DATASOURCE_PASSWORD: sale_password
    depends_on:
      - postgres
    networks:
      - sale-network

volumes:
  postgres_data:

networks:
  sale-network:
    driver: bridge
