spring:
  application:
    name: sale
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sale_market
    username: sale_user
    password: sale_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  liquibase:
    change-log: classpath:/db/changelog/master.xml

jwt:
  access:
    secret: "zJH9DkLkP0Qm7aSxvT2UfGhR1XyN8cLm"
    expiration: 900000
  refresh:
    secret: "nB2RtQyL8aSm0XpZoF5GhHjW9uVtCeKl"
    expiration: 1209600000

server:
  url: http://localhost:8080
  port: 8080

logging:
  level:
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always